on:
  release:
    types:
    - created

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Node.js
    - uses: actions/setup-node@v2
      with:
        node-version: 15

    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Install
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: |
        yarn install

    - name: Deploy
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
      run: yarn vsce publish --yarn

